### ISSUE TITLE
Datadog logs?

### ISSUE THREAD

**Issue by Noxime** [mcasper/dogstatsd-rs#19]
https://www.datadoghq.com/blog/announcing-logs/

Datadog now has log support, which I would really love to use. If you have time, would you mind taking a look at that?

**Comment by mcasper** [comment]
Hey @Noxime! It looks like logs are all going to be handled by the Datadog agent (usually seen as dd-agent), rather than through Dogstatsd. So if you want to use it, you'll need to set up the integration within the agent itself, not through this library

**Comment by Noxime** [comment]
Ah, that is unfortunate. I was hoping it was possible after seeing [this section](https://docs.datadoghq.com/logs/#stream-logs-through-tcp-udp) in the docs. Thank you for your time and thank you for your amazing library!
