### ISSUE TITLE
DataDog Configuration not documented

### ISSUE THREAD

**Issue by fatbasstard** [mcasper/dogstatsd-rs#38]
Hi all, maybe a dumb question, but let's ask anyway :D 

We've got some Rust Lambda's running and we want to add custom metrics, this library looks great, but I'm wondering what the approach if for configuring DataDog (API key etc).

Is there any example for that?

**Comment by mcasper** [comment]
Totally fine, just a case of mistaken identity :) 

This library only sends metrics to DataDog through a statsd client, it doesn't use DataDog's metrics APIs directly. 

You're probably looking for a Rust Datadog API Client, something like https://github.com/jdrouet/datadog-client (though I've never used it)

**Comment by fatbasstard** [comment]
Yes, got it indeed. Missed it in the rush I guess, thanks. I got this as well: https://docs.datadoghq.com/developers/dogstatsd/?tab=hostagent
