### ISSUE TITLE
`Client` `timing` function should accept `u128` instead of `i64`

### ISSUE THREAD

**Issue by cottinisimone** [mcasper/dogstatsd-rs#40]
Since a duration of an execution is supposed to be greater than 0 i think that it might be better, in `timing` function (and in `TimingMetric` struct too), to use an `u128` instead of `i64`.

Moreover i'm not sure about [this comment](https://github.com/mcasper/dogstatsd-rs/blob/master/src/lib.rs#L402) (`Send your own timing metric in milliseconds`). Maybe i'm wrong, but in [datadog documentation](https://docs.datadoghq.com/real_user_monitoring/browser/monitoring_resource_performance/#resource-timing-and-metrics) is written that `duration` metrics are reported as microseconds.

Thank you in advance and for the library :). We use it really a lot!

**Comment by mcasper** [comment]
Hey @cottinisimone! You're absolutely right that a negative timing doesn't make any sense, and we coud possibly change that type to a `u64` to be more semantically correct, though I think I'd rather let people report the full range of values available in the protocol. A `u128` would be nice, but DogstatsD parses all metric values as a 64 bit float: https://github.com/DataDog/datadog-agent/blob/main/pkg/dogstatsd/parse.go#L137

Regarding the timing metric's units, the docs that you've linked to are for their APM product, which is separate from metrics and statsd. I can't find a clear answer in their statd documentation, but there are two reasons I'm led to believe it's in milliseconds:

* The timing metric's `type`is represented by the string `ms`: https://docs.datadoghq.com/developers/dogstatsd/datagram_shell?tab=metrics
* Datadog's own dogstatsd library for Ruby says it's in milliseconds: https://github.com/DataDog/dogstatsd-ruby/blob/master/lib/datadog/statsd.rb#L271

**Comment by cottinisimone** [comment]
Hey @mcasper,

I saw [this page](https://docs.datadoghq.com/metrics/units/#unit-list ) on datadog doc and i thought it was possible. Maybe i'm wrong.

Anyway i think that an `u64` could be good enough anyway :). I thought that `u128` could be better just because calling `std::time::Instant::now().elapsed().as_millis()` (and ofc for for `as_nanos` too) the returned value is an `u128` but if datadog is not able to process it it's fine an `u64` i think. Moreover i'm a bit confused about why is that a float64 and not an int64 :confused:.

Anyway thank you for your time :)
