### ISSUE TITLE
[Request] Implement Event missing features

### ISSUE THREAD

**Issue by ivoreis** [mcasper/dogstatsd-rs#69]
Hi @mcasper, looking at the library, it seems the implementation is a bit behind the official [Datadog documentation](https://docs.datadoghq.com/developers/dogstatsd/datagram_shell/?tab=events).

Would you be happy to review any PR implementing the missing fields and cut a new release with it?

Thanks

**Comment by mcasper** [comment]
@ivoreis absolutely!

**Comment by ivoreis** [comment]
Great 😄

**Comment by ivoreis** [comment]
Put something together - https://github.com/mcasper/dogstatsd-rs/pull/70. 

See if this makes sense to you or if you'd like to move in a different direction. I've added a new fn to ensure backward compatibility with the existing client calls and also allow future expansion when DD decides to implement additional properties :D 

Feedback welcome @mcasper
